.TH infinity 1 2015/10/27


.SH NAME
infinity \- be infinite

.SH SYNOPSIS
.B infinity 
-m 

use a method that would take up an infinite amount of memory

.B infinity
-r 

use pseudo random numbers 
.SH DESCRIPTION
This program is meant to spit out an infinitely long stream of ones and zeros.

.SH FAQ
.B What's the point of this program? 


The point is to show you how big the universe really is, not just in size but in information.
In this infinitely long stream of ones and zeros there is 
.B everything. 
In this stream is every thought you've ever had both in audio, and text format,
a perfect transcript of your own thoughts as you are having them, every idea that has ever been had, been had but never shared, ever will be had, 
or will never be had either because no one will think of them, or because they are beyond the range of what humans can think. 
In this stream there are ideas that could save the world, and fix all of our problems, or create new ones. 

In this stream there is every movie, song, play, and story ever made, or that ever will be made. There are stories in it that are vastly superior
to anything that has ever been written, or ever will be written, and many of them are ones that every intelligent thing in the entire universe could agree are 
better than anything that's ever been made. There's also an infinite number of stories almost identical to these except for a few typos, 
or the story abruptly ending mid-sentence to dive back into a stream of seemingly random ones and zeros. 

There are solutions to all possible problems, as well as the ultimate explanation of absolutely everything that could finally
finish the goal of Science forever. It contains the entirety of pi, all of wikipedia along with every edit that has ever been made to it, or that ever will be made
to it, as well as the entirety of all information that can be said to "exist on the Internet".

This stream contains the words "Help! I'm trapped in a universe factory!" somewhere in it as well as the image file of the XKCD comic https://xkcd.com/10/ that that quote came from.
In this stream is further context about the universe factory, a perfect description of the entire universe as it is now, and as it has been at any point in the past,
and how it will be in the future.

In this stream is the exact time, and date of your 
.B death. 
Someday you will die, but the stream will continue on.
It is infinite. It will outlast you. It will outlast this program. It will outlast your computer, the Internet, and the human race. In fact it will outlast the entire
Universe for it exists independently of space and time. It was there during the beginning of the Universe. It was there when the Earth formed. It was there
when the dinosaurs roamed the earth, when the first apes walked up-right, and it will be there when the Universe ends; 
for time, and space is meaningless to it, and so are you. To it all things happen at the same time, and the same place.

In this stream 
.B you 
exist as well. There's a perfect description of everything you are in it that could be used to recreate you.
In fact there's an infinite number of such versions of you. Most of which are surrounded by a sea of meaningless ones and zeros; but these "random" bits are only
meaningless to us humans. Any part of this stream could be fed into the right computer program and translated into anything we want it to translate to, even the first
single bit could be fed into a program that only produces one of two possible messages.

Even this man page came from the infinite stream. All information comes from the infinite stream. This entire universe is made of information.
All things are merely arrangements of very small things. The arrangement itself is merely information. With this program you can see everything in the universe, as well
as everything beyond this universe. This stream even contains itself an infinite number of times.

Do you feel small yet?

.SH TECHNICAL NOTE:
This program as of right now spits out TRUE ones and zeros so it will fill your screen up with an infinite number of unreadable characters, and an infinite
(though still paradoxically smaller) number of 
.B READABLE 
characters.

.SH LICENSE:
This program is under every software license that has ever been written, ever will be written, or that software companies wish they could write, but can't
because they're too cowardly to and/or haven't thought to write. If you use this program you will immediately be sued by me for violating an **infinite** number
of terms that contradict one another that you have agreed to. Of course not using this software will also get you sued for violating an **infinite** number
of terms that you didn't agree too but that claim that you don't need to agree to. An infinite number of these lawsuits will not stand up in court.
(I'm kidding of course).
